### ISSUE TITLE
feature request: nice way to add environment variables

### ISSUE THREAD

**Issue by Dushistov** [kwrooijen/cargo.el#44]
Use case

Some times when I run tests I need backtrace (`RUST_BACKTRACE=1`),
but need it only in 10% cases, in 90% cases `panic!` message enough by itself,
and backtrace is overflow compilation buffer, make it harder to read `panic!` message.

Yes, I know about `cargo-process--enable-rust-backtrace`, but I want to change
it online without much efforts, plus see bellow.

Also time to time I need `debug!`, `trace!` output during test run,
I can do it via `RUST_LOG=module=debug`, but again I don't need it permanently.

So what about adding interactive commands like `cargo-add-env` and `cargo-clear-env`?

**Comment by kwrooijen** [comment]
If you want to add environment variables inside emacs on the fly, you could use `M-:` and run:
```` Emacs Lisp
(setenv "RUST_BACKTRACE" "1")
````
And remove it via:
```` Emacs Lisp
(setenv "RUST_BACKTRACE" nil)
````

I'm not sure how adding a custom function for this would be beneficial. env variables are also stored together, so in order to distinguish rust vars we'd have to keep track of that. Which of course is possible.

Another option for you is to create a custom function to toggle flags (if fast toggling of specific flags is what you need)

for example:

```` Emacs Lisp
(defun toggle-rust-backtrace ()
  (interactive)
  (if (getenv "RUST_BACKTRACE")
      (setenv "RUST_BACKTRACE" nil)
    (setenv "RUST_BACKTRACE" "1")))
````

Maybe something like this could be helpful to you?

**Comment by kwrooijen** [comment]
Feel free to re-open if this isn't the solution you were hoping for.
